export const LAB_TEST_PAGE = '/lab-test'
export const LAB_TEST_SINGLE_ITEM_PAGE = '/lab-test/single-item'
export const LAB_TEST_INFO_PAGE = '/lab-test/info'
export const LOGIN_PAGE = '/login'
export const DASHBOARD_PAGE = '/dashboard'
export const DINING_PAGE = '/dining'
