export const LAB_TEST_PAGE = '/lab-test'
export const LAB_TEST_SINGLE_ITEM_PAGE = '/lab-test/single-item'
export const LAB_TEST_INFO_PAGE = '/lab-test/info'
export const LOGIN_PAGE = '/login'
export const DASHBOARD_PAGE = '/dashboard'
export const DINING_PAGE = '/dining'
export const DINING_CHECK_IN_PAGE = '/dining/check-in'
export const DINING_MEAL_SETUP_PAGE = '/dining/meal-setup'
export const MONITOR_SYSTEM_PAGE = '/monitor-system'
export const STICKER_PRINTING_PAGE = '/sticker-printing'
export const SETTING_PAGE = '/setting'
export const PRINTING_STICKER_TEST_PAGE = '/sticker-printing-test'
export const KIOSK_PAGE = '/kiosk'
export const QUEUE_MANAGEMENT_PAGE = '/queue-management'
export const RECEPTION_PAGE = '/reception'
export const MEMBER_PROFILE_PAGE = '/member-profile'
export const IT_MONITOR_ROOM_PAGE = '/it-monitor-room'
export const RADIOLOGY_REPORTING_PAGE = '/radiology-reporting'
export const TEST_PDPA_PAGE = '/test-pdpa'
export const IT_ROOM_PRINTING_PAGE = '/it-room-printing'
export const PHYSICIAN_CONSULTATION_PAGE = '/physician-consultation'
export const PHYSICIAN_CONSULTATION_INFO_PAGE = '/physician-consultation-info'
export const STAFF_MANAGEMENT_PAGE = '/staff-management'
export const STAFF_PROFILE_PAGE = '/staff-profile'
export const STAFF_PROFILE_NEW_PAGE = '/staff-profile-new'
export const HEALTH_MANAGEMENT_CONSULTATION_PAGE =
    '/health-management-consultation'
export const HEALTH_MANAGEMENT_CONSULTATION_INFO_PAGE =
    '/health-management-consultation-info'
export const MUL_REPORT_PAGE = '/MUL-report'
export const PHONE_CONSULTATION_PAGE = '/phone-consultation'
export const PHONE_CONSULTATION_DISTRIBUTE_PAGE =
    '/phone-consultation-distribute'
export const DIETARY_LIFE_STYLE_PAGE = '/dietary-life-style'
export const MAIN_INGREDIENT = '/main-ingredient'
export const NUTRIENT = '/nutrient'
